### ISSUE TITLE
UI discussion

### ISSUE THREAD

**Issue by Xerandael** [Xerandael/medieval-future#3]
The UI should have:

- [ ] #23
- [ ]  a marker on the player unit
- [ ]  a list of icons or names of available actions for the player's unit
- [ ]  mouse interaction for selecting an ability, then selecting targets
- [ ]  keyboard interactions for selecting an ability, then selecting targets
- [ ]  when using an ability, allow selecting the die to use from the unit's die pool.
- [ ]  when hovering over the map in the movement phase, draw movement paths

Useful logic for the ability bar:  https://stackoverflow.com/questions/8508275/how-to-center-a-position-absolute-element#18486387

**Comment by AndrewSwerlick** [comment]
It seems like the list of actions should be outside of the svg, in it's own div that floats at the bottom or top of the map. I'm thinking a dedicated menu.js module which tracks the current selected unit and updates itself

**Comment by Xerandael** [comment]
As for just the ability bar when talking about menus, I agree on its placement.  I think there will be too little logic to warrant a module for it.

If we design the CSS well, then we'll only need a few imperative DOM manipulations to accomplish great things.  When there are very few (on the order of an average of 2 lines per component I estimate), then I think it's actually clearer to scatter them inline with other logic.

I think it wouldn't be worth it to bundle unrelated UI elements into a module.  I'd prefer to mix JS DOM manipulation code and JS game state manipulation code than to try to draw a module boundary between UI and game state.  It makes sense conceptually but I think in practice in code would be more complicated, requiring passing more state and more bookkeeping.

I feel that a lot of this bookkeeping is redundant.  The structure of the flow of game logic is parallel to the structure of the flow of the UI.  Think of the UI as stacks and loops mapping exactly to function calls and loops.  Highly-imperative, but safe, and simple, here's a boiled-away skeletal pseudocode for a hypothetical `game.start` function:

A boiled away skeletal pseudocode for a hypothetical `game.start` function:
```
const start = () => {
  loop {
    for({abilities} of team) {
      const abilityBar = html({element: 'ol', id: 'abilityBar'})
      for({name, onClick, src} of abilities) {
        const abilityTile = abilityBar.html({element: 'li', onClick})
        abilityTile.html({element: 'img', src}) // child nodes require another function call
      }
      // await player input
      abilityBar.destroy() // destroys all children automatically
    }
  }
}
```

I think all of the activity bar display logic will be handled by modern CSS with just the ability tiles' state changes (availability, selection) needing any JavaScript logic.

This is similar to RAII.

I can see a use for some HTML shorthand sort of like in the pseudocode.

**Comment by AndrewSwerlick** [comment]
Let me see if I understand what you're advocating for. The first things you're saying is that
  we're going to have a game loop which builds up the UI again each time based on the current
  state of the game, in an imperative manner. As a result, you're arguing 2 things

  1. We don't need an abstraction like components, because fundamental components are designed to
     allow you to update the UI when state updates. Since we're rebuilding the UI each loop,
     we don't need an abstracting like components to manage "book keeping" for state. Instead we
     just have code that imperatively rebuilds the dom elements up from the relevant data
  2. This second argument is maybe more implicit, but I get the sense that maybe you're arguing that
     we don't even bother with any kind of abstraction at all, not even breaking out into an isolated
     module or function.

I'll share my thoughts on both, starting with the second.

I do feel strongly that some level of functional abstraction is important here, for two reasons
First, just for basic code level organization, and to help make the main game loop more readable.
Second, because having a seperate function lets us render the action menu in isolation for easier
testing in something like storybook. If we wanted that abstraction without web components, we can
just have a function that destroys the original element, and then rebuilds the new one each time
it's called.

That being said, I also feel less strongly, that at least in this area, a component is probably worth
it, because there's a certain level of book keeping inherit in this UI element. Specifically I think
we have to keep track of ...

1. The DOM element current hosting this abilities menu
2. The valid keymap for keyboard shortcuts for current abilities

We could store these value in module local variables outside of the function closure, but I like web
component for 3 reasons.

1. Using module local variables means only one action menu can exist at a time. While that might be true
   for the actual game, supporting multiple instances during testing and development is helpful
   for being to quickly test out different states of the UI
2. Using module local variables makes debugging slightly harder since we can't quickly access their
   values in the developer console.
3. While the two items above are the only initial pieces of book keeping, I could see extending the UI
   in a number of ways that would lead to more book keeping. Things like
   * Supporting tabbing or moving through the abilities to bring up more details of the ability like a
     description
   * After selecting an ability, and before selecting a target, keeping the selected ability highlighted
     somehow
   * Collapsing or hiding the menu under certain circumstances
   I can see lots of little things like this continuing to come up as we iterate, leading us to a
   component approach anyways.

Like I said, in general I feel less strongly about this. In both cases, I'm willing to go along with what
you think it best since this is primarily your project.

**Comment by Xerandael** [comment]
I hear the underlying concern of being able to put the game (considered as a whole as one state machine) into a particular state and automatically prod at it from there to determine _what makes zis tick_ and _ist es kaput_?

I would like to leave open an alternative exploration I have floating around in my head which involves automated code manipulation as well as loading data into the state machine from files.  If I could have anything?  I wish I could do something like generators.  Safe goto.  My ideal testing framework would let (and enforce) you set all variables in scope up to the line where the test begins, then _goto_ that line of code (regardless of whether branches had to be traversed, what iterations of loops the execution must be in, what functions calls are on the stack).

Largely, I think imperative code is the clearest and that test-driven-development has made us write code for tests rather than tests for code.  I get that that was the point, but I disagree that its effects have been good.

Let me just try this tool idea.  It might suck but I'll at least have shown you what I mean and maybe there'll be something to salvage.  I think I can bust out something good enough for prototyping soonish.

**Comment by AndrewSwerlick** [comment]
Alright, I'll wait and see what you're thinking. I'm curious to see what this alternative pattern might look like

**Comment by Xerandael** [comment]
Note on a pattern I'm exploring:  https://github.com/Xerandael/medieval-future/wiki/FinalizationRegistry
